#!/usr/bin/env python3
"""
Docker Configuration Helper
NETWORKING class - ASE, Informatics | by Revolvix

Configures Docker environment for Week 13 laboratory including
certificate generation and environment file creation.
"""


# ═══════════════════════════════════════════════════════════════════════════════
# SETUP_ENVIRONMENT
# ═══════════════════════════════════════════════════════════════════════════════
import argparse
import subprocess
import sys
import shutil
from pathlib import Path
from typing import Optional


PROJECT_ROOT = Path(__file__).parent.parent



# ═══════════════════════════════════════════════════════════════════════════════
# EXECUTE_OPERATION
# ═══════════════════════════════════════════════════════════════════════════════
def run_command(cmd: list, capture: bool = True) -> tuple:
    """Execute a command and return (returncode, stdout, stderr)."""
    try:
        result = subprocess.run(cmd, capture_output=capture, text=True, timeout=60)
        return result.returncode, result.stdout or "", result.stderr or ""
    except Exception as e:
        return -1, "", str(e)



# ═══════════════════════════════════════════════════════════════════════════════
# RESOURCE_CREATION
# ═══════════════════════════════════════════════════════════════════════════════
def generate_certificates(force: bool = False) -> bool:
    """Generate TLS certificates for MQTT broker."""
    certs_dir = PROJECT_ROOT / "docker" / "configs" / "certs"
    certs_dir.mkdir(parents=True, exist_ok=True)
    
    ca_key = certs_dir / "ca.key"
    ca_crt = certs_dir / "ca.crt"
    server_key = certs_dir / "server.key"
    server_crt = certs_dir / "server.crt"
    
    if not force and ca_crt.exists() and server_crt.exists():
        print("[INFO] Certificates already exist. Use --regenerate-certs to recreate.")
        return True
    
    if not shutil.which("openssl"):
        print("[ERROR] OpenSSL not found in PATH")
        return False
    
    print("Generating CA certificate...")
    code, _, err = run_command([
        "openssl", "req", "-x509", "-newkey", "rsa:2048",
        "-days", "365", "-nodes",
        "-subj", "/CN=Week13-CA",
        "-keyout", str(ca_key),
        "-out", str(ca_crt)
    ])
    if code != 0:
        print(f"[ERROR] CA generation failed: {err}")
        return False
    
    print("Generating server certificate...")
    csr_path = certs_dir / "server.csr"
    
    code, _, err = run_command([
        "openssl", "req", "-newkey", "rsa:2048", "-nodes",
        "-subj", "/CN=week13-mqtt",
        "-keyout", str(server_key),
        "-out", str(csr_path)
    ])
    if code != 0:
        print(f"[ERROR] CSR generation failed: {err}")
        return False
    
    code, _, err = run_command([
        "openssl", "x509", "-req", "-days", "365",
        "-in", str(csr_path),
        "-CA", str(ca_crt),
        "-CAkey", str(ca_key),
        "-CAcreateserial",
        "-out", str(server_crt)
    ])
    if code != 0:
        print(f"[ERROR] Certificate signing failed: {err}")
        return False
    
    # Cleanup
    csr_path.unlink(missing_ok=True)
    (certs_dir / "ca.srl").unlink(missing_ok=True)
    
    print("[OK] Certificates generated successfully")
    return True



# ═══════════════════════════════════════════════════════════════════════════════
# RESOURCE_CREATION
# ═══════════════════════════════════════════════════════════════════════════════
def create_env_file(
    mqtt_plain: int = 1883,
    mqtt_tls: int = 8883,
    dvwa: int = 8080,
    vsftpd: int = 2121,
    backdoor: int = 6200
) -> bool:
    """Create .env file for Docker Compose."""
    env_file = PROJECT_ROOT / "docker" / ".env"
    
    content = f"""# Week 13 Docker Environment Configuration
# Generated by configure_docker.py
# NETWORKING class - ASE, Informatics | by Revolvix

# MQTT Broker Ports
MQTT_PLAIN_PORT={mqtt_plain}
MQTT_TLS_PORT={mqtt_tls}

# DVWA (Damn Vulnerable Web Application)
DVWA_HOST_PORT={dvwa}

# vsftpd Service
VSFTPD_HOST_PORT={vsftpd}
VSFTPD_BACKDOOR_HOST_PORT={backdoor}
"""
    
    env_file.write_text(content)
    print(f"[OK] Environment file created: {env_file}")
    print(f"     MQTT Plain: localhost:{mqtt_plain}")
    print(f"     MQTT TLS:   localhost:{mqtt_tls}")
    print(f"     DVWA:       http://localhost:{dvwa}")
    print(f"     vsftpd:     localhost:{vsftpd}")
    print(f"     Backdoor:   localhost:{backdoor}")
    return True



# ═══════════════════════════════════════════════════════════════════════════════
# VERIFY_PREREQUISITES
# ═══════════════════════════════════════════════════════════════════════════════
def verify_docker() -> bool:
    """Verify Docker is available and running."""
    if not shutil.which("docker"):
        print("[ERROR] Docker not found in PATH")
        return False
    
    code, _, _ = run_command(["docker", "info"])
    if code != 0:
        print("[ERROR] Docker daemon is not running")
        return False
    
    code, _, _ = run_command(["docker", "compose", "version"])
    if code != 0:
        print("[ERROR] Docker Compose not available")
        return False
    
    print("[OK] Docker is ready")
    return True



# ═══════════════════════════════════════════════════════════════════════════════
# MAIN_ENTRY_POINT
# ═══════════════════════════════════════════════════════════════════════════════
def main() -> int:
    """Main configuration routine."""
    parser = argparse.ArgumentParser(
        description="Configure Docker environment for Week 13 laboratory"
    )
    parser.add_argument(
        "--regenerate-certs",
        action="store_true",
        help="Force regeneration of TLS certificates"
    )
    parser.add_argument(
        "--mqtt-plain-port",
        type=int,
        default=1883,
        help="MQTT plaintext port (default: 1883)"
    )
    parser.add_argument(
        "--mqtt-tls-port",
        type=int,
        default=8883,
        help="MQTT TLS port (default: 8883)"
    )
    parser.add_argument(
        "--dvwa-port",
        type=int,
        default=8080,
        help="DVWA HTTP port (default: 8080)"
    )
    parser.add_argument(
        "--vsftpd-port",
        type=int,
        default=2121,
        help="vsftpd FTP port (default: 2121)"
    )
    parser.add_argument(
        "--backdoor-port",
        type=int,
        default=6200,
        help="Backdoor stub port (default: 6200)"
    )
    
    args = parser.parse_args()
    
    print("=" * 60)
    print("Docker Configuration for Week 13 Laboratory")
    print("NETWORKING class - ASE, Informatics | by Revolvix")
    print("=" * 60)
    print()
    
    # Verify Docker
    if not verify_docker():
        return 1
    
    # Generate certificates
    if not generate_certificates(force=args.regenerate_certs):
        return 1
    
    # Create environment file
    if not create_env_file(
        mqtt_plain=args.mqtt_plain_port,
        mqtt_tls=args.mqtt_tls_port,
        dvwa=args.dvwa_port,
        vsftpd=args.vsftpd_port,
        backdoor=args.backdoor_port
    ):
        return 1
    
    print()
    print("[OK] Docker configuration complete")
    print()
    print("Next step: python scripts/start_lab.py")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
