"""Shared utility helpers for Week 6 network applications."""

from __future__ import annotations

from .network_utils import (
    DEFAULT_BUFFER_SIZE,
    DEFAULT_TIMEOUT,
    CONTROLLER_PORT,
    DNS_PORT,
    FTP_PORT,
    GATEWAY,
    H1_IP,
    H2_IP,
    H3_IP,
    HTTP_PORT,
    PROXY_PORT,
    SERVER_IP,
    SSH_PORT,
    SUBNET,
    TCP_APP_PORT,
    UDP_APP_PORT,
    WEEK,
    WEEK_PORT_BASE,
    WEEK_PORT_RANGE,
    SocketConfig,
    add_common_args,
    create_tcp_socket,
    create_udp_socket,
    is_valid_ip,
    is_valid_port,
    is_week_port,
    print_week_info,
    setup_logging,
)


__all__ = [
    "WEEK",
    "SUBNET",
    "GATEWAY",
    "H1_IP",
    "H2_IP",
    "H3_IP",
    "SERVER_IP",
    "TCP_APP_PORT",
    "UDP_APP_PORT",
    "HTTP_PORT",
    "PROXY_PORT",
    "DNS_PORT",
    "FTP_PORT",
    "SSH_PORT",
    "CONTROLLER_PORT",
    "WEEK_PORT_BASE",
    "WEEK_PORT_RANGE",
    "DEFAULT_TIMEOUT",
    "DEFAULT_BUFFER_SIZE",
    "SocketConfig",
    "setup_logging",
    "create_tcp_socket",
    "create_udp_socket",
    "is_valid_ip",
    "is_valid_port",
    "is_week_port",
    "add_common_args",
    "print_week_info",
]
